# SCREEN CONSTANTS
INITIAL_SCREEN_SIZE = (288, 512)
SCREEN_SIZE_MULTIPLIER = 2
SCREEN_WIDTH = INITIAL_SCREEN_SIZE[0] * SCREEN_SIZE_MULTIPLIER
SCREEN_HEIGHT = INITIAL_SCREEN_SIZE[1] * SCREEN_SIZE_MULTIPLIER

# GAME PARAMETERS

FPS = 60
INITIAL_GAME_SPEED = 3
GAME_ACCELERATION_PER_SECOND = 0.01
GRAVITY = 0.3
GAME_OVER_SCREEN_TIME = 3

# BIRD CONSTANTS

BIRD_INITIAL_LOCATION = [SCREEN_WIDTH / 4, SCREEN_HEIGHT / 2 - 100]
BIRD_LIFT = -7
BIRD_FLAP_SPEED_THRESHOLD = 3
BIRD_ROTATION_SPEED = 3

# PIPE CONSTANTS

PIPE_INITIAL_LOCATION_X = 600
PIPE_VERTICAL_GAP = 200
PIPE_HORIZONTAL_GAP = 350



# SOUND PATHS
POINT_SOUND_PATH = "./audio/point.wav"
GAME_OVER_SOUND_PATH = "./audio/die.wav"
BIRD_JUMP_SOUND_PATH = "./audio/wing.wav"

# SPRITE PATHS

NUMBERS_SPRITE_PATHS = [f"./sprites/numbers/{i}.png" for i in range(10)]
GAME_OVER_SPRITE_PATH = "./sprites/gameover.png"
BASE_SPRITE_PATH = "./sprites/base.png"
PIPE_SPRITE_PATH = "./sprites/pipe-green.png"
BIRD_SPRITE_STATES = ['mid', 'down', 'up']
BIRD_SPRITE_PATHS = {state: f"./sprites/yellowbird-{state}flap.png" for state in BIRD_SPRITE_STATES}
BACKGROUND_SPRITE_PATH = "./sprites/background-day.png"
